# Generated by Django 3.2.5 on 2021-07-22 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=100)),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Referencia', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Existencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('NIT', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.cliente')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Hora', models.TimeField(auto_now_add=True)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.empleado')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cantidad', models.IntegerField()),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.producto')),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cantidad', models.IntegerField()),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.pedido')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.producto')),
            ],
        ),
    ]
