# Generated by Django 3.2.5 on 2021-07-26 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('costoHoras', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas', models.IntegerField()),
                ('horasDominicales', models.IntegerField()),
                ('horasExtra', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datos.empleado')),
            ],
        ),
    ]
