# Generated by Django 3.2.5 on 2021-07-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Estado',
            field=models.CharField(max_length=10),
        ),
    ]
