# Generated by Django 3.2.5 on 2021-07-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0004_auto_20210726_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='Password',
            field=models.CharField(default=models.IntegerField(primary_key=True, serialize=False), max_length=100),
        ),
    ]
