# Generated by Django 3.2.5 on 2021-07-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0005_empleado_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
