# Generated by Django 3.2.5 on 2021-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0006_alter_empleado_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
