# Generated by Django 3.2.5 on 2021-07-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0007_empleado_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
